export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'

export const SHOW_PRODUCTS = 'SHOW_PRODUCTS'
export const SHOW_PRODUCTS_SUCCESS = 'SHOW_PRODUCTS_SUCCESS'
export const SHOW_PRODUCTS_ERROR = 'SHOW_PRODUCTS_ERROR'

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE'
export const DELETED_PRODUCT_SUCCESS = 'DELETED_PRODUCT_SUCCESS'
export const DELETED_PRODUCT_ERROR = 'DELETED_PRODUCT_ERROR'